service: exampleapi

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 512
  environment:
    TABLE_NAME: ${self:custom.tableName}
  apiKeys:
    - ${opt:stage}-ExampleApi

plugins:
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-Service
  tableThroughputs:
    prod: 1
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

functions:
  createLocalDb:
    handler: handlers.createLocalDb
    events:
      - http:
          path: create-local-db
          method: get
  getAppVersion:
    handler: handlers.getAppVersion
    events:
      - http:
          path: version
          method: get
          private: true
  getService:
    handler: handlers.getService
    events:
      - http:
          path: services
          method: get
  createService:
    handler: handlers.createService
    events:
      - http:
          path: services
          method: post
          cors: true
  deleteService:
    handler: handlers.deleteService
    events:
      - http:
          path: services/{dockerPort}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                dockerPort: true

resources:
  - ${file(resources/dynamodb-table.yml)}
